### ISSUE TITLE
adding type_code to schema

### ISSUE THREAD

**Issue by ghost** [dobtco/openrfps-scrapers#10]
for safekeeping, i'm moving the conversation about ITB/RFQ/RFP tagging out of the PR comments (#8) and into its own issue.

**summary of discussion:**
-  Requests for Proposals (RFPs), Invitations to Bid (ITBs), and Request for Quotes (RFQs) are all distinct procurement vehicles
-  agencies often conflate the different vehicles when they shouldn't, and government websites often lump the three together as well. Sometimes there's a type field in the information table and sometimes the only hint about the type of procurement is in the `id` prefix. ([Maryland](https://emaryland.buyspeed.com/bso/external/publicBids.sdo) and [Idaho](http://ipro.sicomm.net/IPRO/) are some examples)
-  it could be good to have a `type_code` field in the openrfps schema that species whether the contracting opportunity is an RFP, ITB, or RFQ; vendors probably will want to check multiple types of opportunities, and having a `type_code` field will allow for more powerful faceting and filtering in the search.

**arguments against adding this field in the near-term:**
-  `type_code` could introduce a nontrivial amount of complexity to the scraper writing process, if only because the differences between ITBs, RFPs, and RFQs are not the easiest to understand and someone new to the process could end up getting pretty confused about what to do with that field.
-  it potentially distracts from the focus on RFPs in the early days of the project, which to me also seems like a nontrivial issue.

**potential arguments in favor of adding this field in the near-term:**
-  if distinguishing between these types of procurement vehicles in the long-term is of interest, adding it now will allow more history to be preserved and will help avoid a potentially messy backfill process. to explain my thinking:
  -  the best case scenario is Idaho, where the id is prefixed by either `RFQ`, `RFP`, or `ITB`; this means that at any time you can take the required `id` field and use it to create a `type_code` field.
  -  some government sites, like Maryland's, put the `type_code` into a separate field and don't surface identifying information anywhere else, which likely means having to refactor the scraper and run it against the procurement site for the whole backhistory.
  -  in this scenario, ideally the links to the old opportunities are still active and you're able to backfill; however, if the links don't work, you can't rescrape the field and you won't have `type_code` information for the historical data.

[apologies for the insane length of this issue; hopefully this is at least a little bit useful in some tiny way. and massive thanks to @sidburgess for patiently explaining the nuances in these procurement vehicles to a government operations ignoramus like me.]

**Comment by ajb** [comment]
Awesome. I'm in favor of adding it.

**Comment by ghost** [comment]
Works for me; thanks, @adamjacobbecker! I'll close this issue this weekend with a PR that has these changes along with a set of scrapers for both Alabama ITBs and RFPs.

**Comment by ajb** [comment]
Theoretically, we should also change the name of our "model" (and filenames) to "Solicitation" instead of "RFP".

**Comment by ghost** [comment]
Ah, you beat me to the punch with the PR — was planning to do it last night but things got too hectic. Thanks, Adam.
