### ISSUE TITLE
States, cities and counties. What about school districts?

### ISSUE THREAD

**Issue by jefflundberg** [dobtco/openrfps-scrapers#13]
It looks like states, cities, and counties have a place to live. What about school districts?

For example:
/state/cities/city-name/
/state/counties/county-name/
**/state/schools/district-name/**

Things to consider: 
- Some states have a single state-wide school district
- Some are county-wide
- Some school districts are just departments of a city (i.e. not a separate entity)
- Some districts are city-based
- Some states have a combination of the above

Thoughts?

**Comment by ajb** [comment]
Thanks for opening this, Jeff. I like `*/schools/*` as a format, too.

I've added a bit more info to the README in https://github.com/dobtco/openrfps-scrapers/commit/84d7fb154393250ba8e4513b06a221bd08bfc25f.
