### ISSUE TITLE
URL validation

### ISSUE THREAD

**Issue by eabh** [dobtco/openrfps-scrapers#14]
I wrote a scraper for New Hampshire and found that it passes the test bank except that the regular expression for urls disallows those with embedded spaces. However the site contains attachments whose urls have embedded spaces. I tried converting them to '%20' but that is also regarded as invalid. Thus I have a working scraper that produces what I think are correct results but it fails the test. Shall I make a pull request for it anyway? Please advise?

**Comment by ajb** [comment]
Sorry about that, looks like I grabbed a shitty regular expression. You should be all set now!
