### ISSUE TITLE
Add "type" to scraped results

### ISSUE THREAD

**Issue by ajb** [dobtco/openrfps-scrapers#18]
@eabh can you take a quick peek at this? sorry, i just added this field to the schema this morning :P

https://github.com/dobtco/openrfps-scrapers/blob/master/OUTPUT.md#rfp-types

**Comment by eabh** [comment]
I have added 'type' to the NH scraper. Do you need another pull request for that?

**Comment by ajb** [comment]
Yep, that would be great. If you can merge this master branch and rebase your changes on top, that would be amazing.
