### ISSUE TITLE
Visual Dashboard

### ISSUE THREAD

**Issue by sidburgess** [dobtco/openrfps-scrapers#2]
Would be great to have a visual dashboard like: http://us-city.census.okfn.org/ to track how open agency RFP's are.

**Comment by ajb** [comment]
Closing this for now -- I'd like to keep this repo's issues limited to scrapers, and move ideation somewhere else. For now, that place could be https://github.com/dobtco/openrfps-site/issues, but we can define a more appropriate place sometime soon.
