### ISSUE TITLE
Documentation, How Do I Execute?

### ISSUE THREAD

**Issue by DunnBrokeIT** [dobtco/openrfps-scrapers#27]
Good Day, I have an interest in your project and could perhaps contribute in some ways.  I am not a coder but I did open one of the scraper files and it’s pretty easy, on the coffee script files no not so much.  At any rate my firm subscribes to many of these services and I would like to run your app in parallel to see the differences in results.  I have collected a good many RFP sites and search terms.  I downloaded your package but could not determine how to execute even a test scrape.  I could do this on either Windows or Linux.  Thanks for any direction you may offer.

Cheers

**Comment by ajb** [comment]
Hey there, take a look at my answer in https://github.com/dobtco/openrfps-scrapers/issues/28.
