### ISSUE TITLE
Question: how to use

### ISSUE THREAD

**Issue by morenoh149** [dobtco/openrfps-scrapers#28]
This looks like a good project. Is it self hosted? Or is there a site I can visit to see rfps?

**Comment by ajb** [comment]
Hi Harry, thanks for your interest. At the current moment, you'll need to clone the repo and follow the instructions to run the scrapers yourself. The server component has a repo at https://github.com/dobtco/openrfps-server, but it's currently empty.

**Comment by DunnBrokeIT** [comment]
Follow the instructions from where?

Cheers!

**Comment by morenoh149** [comment]
@DunnBrokeIT read from here https://github.com/dobtco/openrfps-scrapers#install-dependencies down
